#!/usr/bin/env bash
set -e

echo "🏗  Scaffolding SteriyMed — Global Ultimate tree..."

# ===================================================================
# DIRECTORIES
# ===================================================================
dirs=(
  # ---------- lib/core ----------
  "lib/core/config"
  "lib/core/network/interceptors"
  "lib/core/errors"
  "lib/core/storage/outbox"
  "lib/core/sync"
  "lib/core/router/guards"
  "lib/core/theme"
  "lib/core/utils/formatters"
  "lib/core/utils/extensions"
  "lib/core/analytics"
  "lib/core/crash"
  "lib/core/permissions"
  "lib/core/lifecycle"
  "lib/core/constants"

  # ---------- lib/shared ----------
  "lib/shared/widgets/buttons"
  "lib/shared/widgets/inputs"
  "lib/shared/widgets/feedback"
  "lib/shared/widgets/badges"
  "lib/shared/widgets/lists"
  "lib/shared/widgets/cards"
  "lib/shared/widgets/layout"
  "lib/shared/widgets/media"
  "lib/shared/widgets/forms"
  "lib/shared/widgets/timeline"
  "lib/shared/widgets/misc"
  "lib/shared/extensions"

  # ---------- features/auth ----------
  "lib/features/auth/data/models"
  "lib/features/auth/data/datasources"
  "lib/features/auth/data/repositories"
  "lib/features/auth/presentation/bloc"
  "lib/features/auth/presentation/screens"
  "lib/features/auth/presentation/widgets"

  # ---------- features/dashboard ----------
  "lib/features/dashboard/data/models"
  "lib/features/dashboard/data/datasources"
  "lib/features/dashboard/data/repositories"
  "lib/features/dashboard/presentation/cubit"
  "lib/features/dashboard/presentation/screens"
  "lib/features/dashboard/presentation/widgets"

  # ---------- features/scanner ----------
  "lib/features/scanner/data/models"
  "lib/features/scanner/presentation/bloc"
  "lib/features/scanner/presentation/screens"
  "lib/features/scanner/presentation/widgets"

  # ---------- features/labels ----------
  "lib/features/labels/data/models"
  "lib/features/labels/data/datasources"
  "lib/features/labels/data/repositories"
  "lib/features/labels/presentation/bloc"
  "lib/features/labels/presentation/screens"
  "lib/features/labels/presentation/widgets"

  # ---------- features/patients ----------
  "lib/features/patients/data/models"
  "lib/features/patients/data/datasources"
  "lib/features/patients/data/repositories"
  "lib/features/patients/presentation/bloc"
  "lib/features/patients/presentation/screens"
  "lib/features/patients/presentation/widgets"

  # ---------- features/cycles ----------
  "lib/features/cycles/data/models"
  "lib/features/cycles/data/datasources"
  "lib/features/cycles/data/repositories"
  "lib/features/cycles/presentation/bloc"
  "lib/features/cycles/presentation/screens"
  "lib/features/cycles/presentation/widgets"

  # ---------- features/stock ----------
  "lib/features/stock/data/models"
  "lib/features/stock/data/datasources"
  "lib/features/stock/data/repositories"
  "lib/features/stock/presentation/bloc"
  "lib/features/stock/presentation/screens"
  "lib/features/stock/presentation/widgets"

  # ---------- features/purchases ----------
  "lib/features/purchases/data/models"
  "lib/features/purchases/data/datasources"
  "lib/features/purchases/data/repositories"
  "lib/features/purchases/presentation/bloc"
  "lib/features/purchases/presentation/screens"
  "lib/features/purchases/presentation/widgets"

  # ---------- features/prosthetic ----------
  "lib/features/prosthetic/data/models"
  "lib/features/prosthetic/data/datasources"
  "lib/features/prosthetic/data/repositories"
  "lib/features/prosthetic/presentation/bloc"
  "lib/features/prosthetic/presentation/screens"
  "lib/features/prosthetic/presentation/widgets"

  # ---------- features/alerts ----------
  "lib/features/alerts/data/models"
  "lib/features/alerts/data/datasources"
  "lib/features/alerts/data/repositories"
  "lib/features/alerts/presentation/bloc"
  "lib/features/alerts/presentation/screens"
  "lib/features/alerts/presentation/widgets"

  # ---------- features/history ----------
  "lib/features/history/data/models"
  "lib/features/history/data/datasources"
  "lib/features/history/data/repositories"
  "lib/features/history/presentation/bloc"
  "lib/features/history/presentation/screens"
  "lib/features/history/presentation/widgets"

  # ---------- features/settings ----------
  "lib/features/settings/data/models"
  "lib/features/settings/data/datasources"
  "lib/features/settings/data/repositories"
  "lib/features/settings/presentation/bloc"
  "lib/features/settings/presentation/screens"
  "lib/features/settings/presentation/widgets"

  # ---------- features/sync ----------
  "lib/features/sync/presentation/bloc"
  "lib/features/sync/presentation/screens"
  "lib/features/sync/presentation/widgets"

  # ---------- features/shell ----------
  "lib/features/shell/presentation/screens"
  "lib/features/shell/presentation/widgets"

  # ---------- features/onboarding ----------
  "lib/features/onboarding/presentation/bloc"
  "lib/features/onboarding/presentation/screens"
  "lib/features/onboarding/presentation/widgets"

  # ---------- di / l10n ----------
  "lib/di"
  "lib/l10n/generated"

  # ---------- test ----------
  "test/unit/core"
  "test/unit/storage"
  "test/unit/features/prosthetic"
  "test/unit/features/cycles"
  "test/unit/features/stock"
  "test/bloc"
  "test/widget"
  "test/golden/goldens"
  "test/fixtures"
  "test/mocks"
  "test/helpers"

  # ---------- integration_test ----------
  "integration_test/journeys"
  "integration_test/support"
  "integration_test/drivers"

  # ---------- assets ----------
  "assets/images/empty_states"
  "assets/images/illustrations"
  "assets/images/icons"
  "assets/fonts"
  "assets/config"

  # ---------- scripts / fastlane / .github / docs ----------
  "scripts"
  "fastlane/metadata/android/fr-FR/changelogs"
  "fastlane/metadata/android/fr-FR/images/phoneScreenshots"
  "fastlane/metadata/ios/fr-FR/screenshots"
  "fastlane/certs"
  ".github/workflows"
  "docs/ui-reference"
)

for d in "${dirs[@]}"; do mkdir -p "$d"; done
echo "   ✓ ${#dirs[@]} directories"

# ===================================================================
# FILES
# ===================================================================
files=(
  # ----- lib root -----
  "lib/main.dart"
  "lib/bootstrap.dart"
  "lib/app.dart"

  # ----- core/config -----
  "lib/core/config/env.dart"
  "lib/core/config/api_endpoints.dart"
  "lib/core/config/app_config.dart"
  "lib/core/config/build_info.dart"

  # ----- core/network -----
  "lib/core/network/dio_client.dart"
  "lib/core/network/dio_factory.dart"
  "lib/core/network/network_info.dart"
  "lib/core/network/interceptors/auth_interceptor.dart"
  "lib/core/network/interceptors/error_interceptor.dart"
  "lib/core/network/interceptors/idempotency_interceptor.dart"
  "lib/core/network/interceptors/logging_interceptor.dart"
  "lib/core/network/interceptors/retry_interceptor.dart"

  # ----- core/errors -----
  "lib/core/errors/api_exception.dart"
  "lib/core/errors/error_mapper.dart"
  "lib/core/errors/failure.dart"
  "lib/core/errors/error_codes.dart"

  # ----- core/storage -----
  "lib/core/storage/secure_storage.dart"
  "lib/core/storage/token_storage.dart"
  "lib/core/storage/session_store.dart"
  "lib/core/storage/key_value_store.dart"
  "lib/core/storage/outbox/outbox_item.dart"
  "lib/core/storage/outbox/outbox_operation.dart"
  "lib/core/storage/outbox/outbox_status.dart"
  "lib/core/storage/outbox/outbox_store.dart"
  "lib/core/storage/outbox/outbox_repository.dart"
  "lib/core/storage/outbox/sync_engine.dart"
  "lib/core/storage/outbox/sync_result.dart"

  # ----- core/sync -----
  "lib/core/sync/connectivity_service.dart"
  "lib/core/sync/sync_status.dart"
  "lib/core/sync/sync_status_cubit.dart"

  # ----- core/router -----
  "lib/core/router/app_router.dart"
  "lib/core/router/routes.dart"
  "lib/core/router/route_names.dart"
  "lib/core/router/guards/auth_guard.dart"
  "lib/core/router/guards/role_guard.dart"

  # ----- core/theme -----
  "lib/core/theme/app_theme.dart"
  "lib/core/theme/light_theme.dart"
  "lib/core/theme/dark_theme.dart"
  "lib/core/theme/tokens.dart"
  "lib/core/theme/colors.dart"
  "lib/core/theme/typography.dart"
  "lib/core/theme/spacing.dart"
  "lib/core/theme/radius.dart"
  "lib/core/theme/shadows.dart"

  # ----- core/utils -----
  "lib/core/utils/debouncer.dart"
  "lib/core/utils/throttler.dart"
  "lib/core/utils/idempotency_key.dart"
  "lib/core/utils/validators.dart"
  "lib/core/utils/logger.dart"
  "lib/core/utils/pii_scrubber.dart"
  "lib/core/utils/formatters/date_formatter.dart"
  "lib/core/utils/formatters/currency_formatter.dart"
  "lib/core/utils/formatters/phone_formatter.dart"
  "lib/core/utils/extensions/string_ext.dart"
  "lib/core/utils/extensions/datetime_ext.dart"
  "lib/core/utils/extensions/context_ext.dart"
  "lib/core/utils/extensions/list_ext.dart"

  # ----- core (analytics/crash/perm/lifecycle/constants) -----
  "lib/core/analytics/analytics_service.dart"
  "lib/core/analytics/analytics_events.dart"
  "lib/core/crash/crash_reporter.dart"
  "lib/core/permissions/camera_permission.dart"
  "lib/core/permissions/notification_permission.dart"
  "lib/core/lifecycle/app_lifecycle_observer.dart"
  "lib/core/constants/app_constants.dart"
  "lib/core/constants/storage_keys.dart"
  "lib/core/constants/pagination.dart"

  # ----- shared/widgets -----
  "lib/shared/widgets/buttons/primary_button.dart"
  "lib/shared/widgets/buttons/secondary_button.dart"
  "lib/shared/widgets/buttons/ghost_button.dart"
  "lib/shared/widgets/buttons/danger_button.dart"
  "lib/shared/widgets/buttons/icon_action_button.dart"
  "lib/shared/widgets/inputs/app_text_field.dart"
  "lib/shared/widgets/inputs/app_dropdown.dart"
  "lib/shared/widgets/inputs/app_date_picker.dart"
  "lib/shared/widgets/inputs/app_search_field.dart"
  "lib/shared/widgets/inputs/app_number_stepper.dart"
  "lib/shared/widgets/inputs/app_text_area.dart"
  "lib/shared/widgets/feedback/loading_view.dart"
  "lib/shared/widgets/feedback/error_view.dart"
  "lib/shared/widgets/feedback/empty_view.dart"
  "lib/shared/widgets/feedback/offline_banner.dart"
  "lib/shared/widgets/feedback/sync_status_badge.dart"
  "lib/shared/widgets/feedback/app_snackbar.dart"
  "lib/shared/widgets/feedback/confirmation_dialog.dart"
  "lib/shared/widgets/badges/status_badge.dart"
  "lib/shared/widgets/badges/severity_badge.dart"
  "lib/shared/widgets/badges/aging_badge.dart"
  "lib/shared/widgets/lists/cursor_paginated_list.dart"
  "lib/shared/widgets/lists/list_tile_skeleton.dart"
  "lib/shared/widgets/lists/list_separator.dart"
  "lib/shared/widgets/cards/app_card.dart"
  "lib/shared/widgets/cards/kpi_card.dart"
  "lib/shared/widgets/cards/info_card.dart"
  "lib/shared/widgets/cards/action_card.dart"
  "lib/shared/widgets/layout/app_scaffold.dart"
  "lib/shared/widgets/layout/app_appbar.dart"
  "lib/shared/widgets/layout/section_header.dart"
  "lib/shared/widgets/layout/divider_labeled.dart"
  "lib/shared/widgets/layout/responsive_layout.dart"
  "lib/shared/widgets/media/app_image.dart"
  "lib/shared/widgets/media/app_avatar.dart"
  "lib/shared/widgets/media/attachment_tile.dart"
  "lib/shared/widgets/media/photo_capture.dart"
  "lib/shared/widgets/media/image_preview.dart"
  "lib/shared/widgets/forms/form_section.dart"
  "lib/shared/widgets/forms/form_field_wrapper.dart"
  "lib/shared/widgets/forms/form_actions.dart"
  "lib/shared/widgets/timeline/timeline_widget.dart"
  "lib/shared/widgets/timeline/timeline_entry.dart"
  "lib/shared/widgets/misc/app_logo.dart"
  "lib/shared/widgets/misc/app_version_label.dart"
  "lib/shared/widgets/misc/environment_badge.dart"
  "lib/shared/widgets/misc/copyable_text.dart"
  "lib/shared/extensions/widget_ext.dart"

  # ----- features/auth -----
  "lib/features/auth/data/models/user_data.dart"
  "lib/features/auth/data/models/tenant_data.dart"
  "lib/features/auth/data/models/login_response.dart"
  "lib/features/auth/data/datasources/auth_remote_datasource.dart"
  "lib/features/auth/data/repositories/auth_repository.dart"
  "lib/features/auth/presentation/bloc/auth_bloc.dart"
  "lib/features/auth/presentation/bloc/auth_event.dart"
  "lib/features/auth/presentation/bloc/auth_state.dart"
  "lib/features/auth/presentation/screens/splash_screen.dart"
  "lib/features/auth/presentation/screens/login_screen.dart"
  "lib/features/auth/presentation/screens/camera_permission_screen.dart"
  "lib/features/auth/presentation/widgets/login_form.dart"

  # ----- features/dashboard -----
  "lib/features/dashboard/data/models/dashboard_data.dart"
  "lib/features/dashboard/data/datasources/dashboard_remote_datasource.dart"
  "lib/features/dashboard/data/repositories/dashboard_repository.dart"
  "lib/features/dashboard/presentation/cubit/dashboard_cubit.dart"
  "lib/features/dashboard/presentation/cubit/dashboard_state.dart"
  "lib/features/dashboard/presentation/screens/dashboard_screen.dart"
  "lib/features/dashboard/presentation/widgets/kpi_row.dart"
  "lib/features/dashboard/presentation/widgets/attention_cards.dart"
  "lib/features/dashboard/presentation/widgets/today_cycles_card.dart"
  "lib/features/dashboard/presentation/widgets/recent_procedures_card.dart"
  "lib/features/dashboard/presentation/widgets/prosthetic_summary_card.dart"

  # ----- features/scanner -----
  "lib/features/scanner/data/models/scan_result.dart"
  "lib/features/scanner/presentation/bloc/scanner_bloc.dart"
  "lib/features/scanner/presentation/bloc/scanner_event.dart"
  "lib/features/scanner/presentation/bloc/scanner_state.dart"
  "lib/features/scanner/presentation/screens/scanner_screen.dart"
  "lib/features/scanner/presentation/widgets/scanner_overlay.dart"
  "lib/features/scanner/presentation/widgets/torch_toggle.dart"
  "lib/features/scanner/presentation/widgets/scan_cooldown_indicator.dart"

  # ----- features/labels -----
  "lib/features/labels/data/models/label_scan_result.dart"
  "lib/features/labels/data/models/label_data.dart"
  "lib/features/labels/data/models/label_usage_data.dart"
  "lib/features/labels/data/datasources/label_remote_datasource.dart"
  "lib/features/labels/data/datasources/label_usage_remote_datasource.dart"
  "lib/features/labels/data/repositories/label_repository.dart"
  "lib/features/labels/data/repositories/label_usage_repository.dart"
  "lib/features/labels/presentation/bloc/label_detail_bloc.dart"
  "lib/features/labels/presentation/bloc/label_usage_bloc.dart"
  "lib/features/labels/presentation/screens/label_detail_screen.dart"
  "lib/features/labels/presentation/screens/label_blocked_screen.dart"
  "lib/features/labels/presentation/screens/label_usage_form_screen.dart"
  "lib/features/labels/presentation/widgets/label_status_header.dart"
  "lib/features/labels/presentation/widgets/label_info_section.dart"
  "lib/features/labels/presentation/widgets/label_usage_history.dart"
  "lib/features/labels/presentation/widgets/label_blocked_banner.dart"

  # ----- features/patients -----
  "lib/features/patients/data/models/patient_data.dart"
  "lib/features/patients/data/datasources/patient_remote_datasource.dart"
  "lib/features/patients/data/repositories/patient_repository.dart"
  "lib/features/patients/presentation/bloc/patient_search_bloc.dart"
  "lib/features/patients/presentation/screens/patient_search_screen.dart"
  "lib/features/patients/presentation/widgets/patient_tile.dart"
  "lib/features/patients/presentation/widgets/patient_picker_sheet.dart"

  # ----- features/cycles -----
  "lib/features/cycles/data/models/cycle_data.dart"
  "lib/features/cycles/data/models/cycle_item_data.dart"
  "lib/features/cycles/data/models/control_test_data.dart"
  "lib/features/cycles/data/models/cycle_attachment_data.dart"
  "lib/features/cycles/data/models/cycle_release_data.dart"
  "lib/features/cycles/data/datasources/cycle_remote_datasource.dart"
  "lib/features/cycles/data/repositories/cycle_repository.dart"
  "lib/features/cycles/presentation/bloc/cycle_list_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_detail_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_create_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_transition_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_items_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_control_tests_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_attachments_bloc.dart"
  "lib/features/cycles/presentation/bloc/cycle_release_bloc.dart"
  "lib/features/cycles/presentation/screens/cycle_list_screen.dart"
  "lib/features/cycles/presentation/screens/cycle_detail_screen.dart"
  "lib/features/cycles/presentation/screens/cycle_create_screen.dart"
  "lib/features/cycles/presentation/screens/cycle_items_screen.dart"
  "lib/features/cycles/presentation/screens/cycle_control_tests_screen.dart"
  "lib/features/cycles/presentation/screens/cycle_attachments_screen.dart"
  "lib/features/cycles/presentation/screens/cycle_release_screen.dart"
  "lib/features/cycles/presentation/widgets/cycle_tile.dart"
  "lib/features/cycles/presentation/widgets/cycle_status_badge.dart"
  "lib/features/cycles/presentation/widgets/cycle_timeline.dart"
  "lib/features/cycles/presentation/widgets/cycle_item_row.dart"
  "lib/features/cycles/presentation/widgets/control_test_row.dart"
  "lib/features/cycles/presentation/widgets/cycle_attachment_grid.dart"
  "lib/features/cycles/presentation/widgets/release_decision_sheet.dart"
  "lib/features/cycles/presentation/widgets/transition_confirm_dialog.dart"

  # ----- features/stock -----
  "lib/features/stock/data/models/stock_level_data.dart"
  "lib/features/stock/data/models/stock_movement_data.dart"
  "lib/features/stock/data/models/location_data.dart"
  "lib/features/stock/data/datasources/stock_remote_datasource.dart"
  "lib/features/stock/data/repositories/stock_repository.dart"
  "lib/features/stock/presentation/bloc/stock_level_list_bloc.dart"
  "lib/features/stock/presentation/bloc/stock_issue_bloc.dart"
  "lib/features/stock/presentation/bloc/stock_adjust_bloc.dart"
  "lib/features/stock/presentation/bloc/stock_transfer_bloc.dart"
  "lib/features/stock/presentation/screens/stock_level_list_screen.dart"
  "lib/features/stock/presentation/screens/stock_issue_screen.dart"
  "lib/features/stock/presentation/screens/stock_adjust_screen.dart"
  "lib/features/stock/presentation/screens/stock_transfer_screen.dart"
  "lib/features/stock/presentation/widgets/stock_level_tile.dart"
  "lib/features/stock/presentation/widgets/low_stock_indicator.dart"
  "lib/features/stock/presentation/widgets/quantity_stepper.dart"
  "lib/features/stock/presentation/widgets/reason_field.dart"
  "lib/features/stock/presentation/widgets/location_picker.dart"

  # ----- features/purchases -----
  "lib/features/purchases/data/models/purchase_order_data.dart"
  "lib/features/purchases/data/models/purchase_order_line_data.dart"
  "lib/features/purchases/data/models/goods_receipt_data.dart"
  "lib/features/purchases/data/models/goods_receipt_line_data.dart"
  "lib/features/purchases/data/datasources/purchase_remote_datasource.dart"
  "lib/features/purchases/data/repositories/purchase_repository.dart"
  "lib/features/purchases/presentation/bloc/purchase_order_list_bloc.dart"
  "lib/features/purchases/presentation/bloc/purchase_order_detail_bloc.dart"
  "lib/features/purchases/presentation/bloc/goods_receipt_bloc.dart"
  "lib/features/purchases/presentation/bloc/receipt_attachment_bloc.dart"
  "lib/features/purchases/presentation/screens/purchase_order_list_screen.dart"
  "lib/features/purchases/presentation/screens/purchase_order_detail_screen.dart"
  "lib/features/purchases/presentation/screens/goods_receipt_screen.dart"
  "lib/features/purchases/presentation/screens/receipt_photo_screen.dart"
  "lib/features/purchases/presentation/widgets/purchase_order_tile.dart"
  "lib/features/purchases/presentation/widgets/purchase_order_status_badge.dart"
  "lib/features/purchases/presentation/widgets/receipt_line_form.dart"
  "lib/features/purchases/presentation/widgets/batch_expiry_fields.dart"
  "lib/features/purchases/presentation/widgets/discrepancy_reason_field.dart"

  # ----- features/prosthetic -----
  "lib/features/prosthetic/data/models/prosthetic_case.dart"
  "lib/features/prosthetic/data/models/prosthetic_case_status.dart"
  "lib/features/prosthetic/data/models/prosthetic_case_history.dart"
  "lib/features/prosthetic/data/models/prosthetic_case_attachment.dart"
  "lib/features/prosthetic/data/models/prosthetic_payment.dart"
  "lib/features/prosthetic/data/models/laboratory.dart"
  "lib/features/prosthetic/data/models/prosthetic_work_type.dart"
  "lib/features/prosthetic/data/models/impression_type.dart"
  "lib/features/prosthetic/data/models/waiting_placement_entry.dart"
  "lib/features/prosthetic/data/models/prosthetic_dashboard.dart"
  "lib/features/prosthetic/data/models/prosthetic_filters.dart"
  "lib/features/prosthetic/data/datasources/prosthetic_remote_datasource.dart"
  "lib/features/prosthetic/data/datasources/prosthetic_status_remote_datasource.dart"
  "lib/features/prosthetic/data/datasources/prosthetic_payment_remote_datasource.dart"
  "lib/features/prosthetic/data/datasources/laboratory_remote_datasource.dart"
  "lib/features/prosthetic/data/datasources/waiting_placement_remote_datasource.dart"
  "lib/features/prosthetic/data/datasources/prosthetic_local_outbox_datasource.dart"
  "lib/features/prosthetic/data/repositories/prosthetic_case_repository.dart"
  "lib/features/prosthetic/data/repositories/prosthetic_status_repository.dart"
  "lib/features/prosthetic/data/repositories/prosthetic_payment_repository.dart"
  "lib/features/prosthetic/data/repositories/laboratory_repository.dart"
  "lib/features/prosthetic/data/repositories/waiting_placement_repository.dart"
  "lib/features/prosthetic/data/repositories/prosthetic_dashboard_repository.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_list_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_case_detail_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_form_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_status_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_payment_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_attachment_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/waiting_placement_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/laboratory_bloc.dart"
  "lib/features/prosthetic/presentation/bloc/prosthetic_dashboard_cubit.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_list_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_case_detail_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_case_create_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_case_edit_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_status_history_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_payment_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_attachment_screen.dart"
  "lib/features/prosthetic/presentation/screens/waiting_placement_screen.dart"
  "lib/features/prosthetic/presentation/screens/prosthetic_dashboard_screen.dart"
  "lib/features/prosthetic/presentation/screens/laboratory_list_screen.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_case_tile.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_status_badge.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_status_stepper.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_timeline.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_payment_block.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_remaining_balance.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_attachment_grid.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_filters_sheet.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_form_section_patient.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_form_section_clinical.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_form_section_lab_dates.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_form_section_notes.dart"
  "lib/features/prosthetic/presentation/widgets/waiting_placement_row.dart"
  "lib/features/prosthetic/presentation/widgets/waiting_placement_aging_badge.dart"
  "lib/features/prosthetic/presentation/widgets/prosthetic_dashboard_cards.dart"
  "lib/features/prosthetic/presentation/widgets/laboratory_picker_sheet.dart"

  # ----- features/alerts -----
  "lib/features/alerts/data/models/alert_data.dart"
  "lib/features/alerts/data/datasources/alert_remote_datasource.dart"
  "lib/features/alerts/data/repositories/alert_repository.dart"
  "lib/features/alerts/presentation/bloc/alert_list_bloc.dart"
  "lib/features/alerts/presentation/bloc/alert_resolve_bloc.dart"
  "lib/features/alerts/presentation/screens/alert_list_screen.dart"
  "lib/features/alerts/presentation/widgets/alert_tile.dart"
  "lib/features/alerts/presentation/widgets/alert_severity_group.dart"
  "lib/features/alerts/presentation/widgets/resolve_confirm_dialog.dart"

  # ----- features/history -----
  "lib/features/history/data/models/audit_event_data.dart"
  "lib/features/history/data/datasources/audit_remote_datasource.dart"
  "lib/features/history/data/repositories/audit_repository.dart"
  "lib/features/history/presentation/bloc/audit_list_bloc.dart"
  "lib/features/history/presentation/bloc/history_filters_cubit.dart"
  "lib/features/history/presentation/screens/audit_list_screen.dart"
  "lib/features/history/presentation/widgets/audit_event_tile.dart"
  "lib/features/history/presentation/widgets/history_filter_bar.dart"
  "lib/features/history/presentation/widgets/history_date_range_picker.dart"

  # ----- features/settings -----
  "lib/features/settings/data/models/profile_data.dart"
  "lib/features/settings/data/models/tenant_profile_data.dart"
  "lib/features/settings/data/datasources/settings_remote_datasource.dart"
  "lib/features/settings/data/repositories/settings_repository.dart"
  "lib/features/settings/presentation/bloc/settings_bloc.dart"
  "lib/features/settings/presentation/bloc/session_bloc.dart"
  "lib/features/settings/presentation/screens/settings_screen.dart"
  "lib/features/settings/presentation/screens/about_screen.dart"
  "lib/features/settings/presentation/widgets/settings_tile.dart"
  "lib/features/settings/presentation/widgets/account_section.dart"
  "lib/features/settings/presentation/widgets/tenant_section.dart"
  "lib/features/settings/presentation/widgets/session_section.dart"
  "lib/features/settings/presentation/widgets/app_info_section.dart"
  "lib/features/settings/presentation/widgets/environment_badge.dart"

  # ----- features/sync -----
  "lib/features/sync/presentation/bloc/sync_status_bloc.dart"
  "lib/features/sync/presentation/screens/sync_queue_screen.dart"
  "lib/features/sync/presentation/widgets/sync_status_banner.dart"
  "lib/features/sync/presentation/widgets/pending_count_badge.dart"
  "lib/features/sync/presentation/widgets/sync_queue_item.dart"
  "lib/features/sync/presentation/widgets/manual_review_dialog.dart"

  # ----- features/shell -----
  "lib/features/shell/presentation/screens/shell_screen.dart"
  "lib/features/shell/presentation/widgets/bottom_nav_bar.dart"
  "lib/features/shell/presentation/widgets/role_aware_nav.dart"
  "lib/features/shell/presentation/widgets/profile_menu.dart"
  "lib/features/shell/presentation/widgets/sync_indicator.dart"

  # ----- features/onboarding -----
  "lib/features/onboarding/presentation/bloc/onboarding_bloc.dart"
  "lib/features/onboarding/presentation/screens/onboarding_screen.dart"
  "lib/features/onboarding/presentation/widgets/onboarding_page.dart"
  "lib/features/onboarding/presentation/widgets/onboarding_indicator.dart"

  # ----- di -----
  "lib/di/di.dart"
  "lib/di/core_di.dart"
  "lib/di/network_di.dart"
  "lib/di/storage_di.dart"
  "lib/di/router_di.dart"
  "lib/di/features_di.dart"

  # ----- l10n -----
  "lib/l10n/app_fr.arb"
  "lib/l10n/l10n.yaml"
  "lib/l10n/generated/app_localizations.dart"
  "lib/l10n/generated/app_localizations_fr.dart"

  # ----- test/unit -----
  "test/test_runner.dart"
  "test/unit/core/error_mapper_test.dart"
  "test/unit/core/idempotency_key_test.dart"
  "test/unit/core/debouncer_test.dart"
  "test/unit/core/validators_test.dart"
  "test/unit/core/pii_scrubber_test.dart"
  "test/unit/core/env_test.dart"
  "test/unit/storage/outbox_store_test.dart"
  "test/unit/storage/sync_engine_test.dart"
  "test/unit/features/prosthetic/prosthetic_status_transition_test.dart"
  "test/unit/features/prosthetic/remaining_balance_test.dart"
  "test/unit/features/prosthetic/waiting_placement_filter_test.dart"

  # ----- test/bloc -----
  "test/bloc/auth_bloc_test.dart"
  "test/bloc/dashboard_cubit_test.dart"
  "test/bloc/scanner_bloc_test.dart"
  "test/bloc/label_detail_bloc_test.dart"
  "test/bloc/label_usage_bloc_test.dart"
  "test/bloc/cycle_list_bloc_test.dart"
  "test/bloc/cycle_transition_bloc_test.dart"
  "test/bloc/stock_issue_bloc_test.dart"
  "test/bloc/goods_receipt_bloc_test.dart"
  "test/bloc/prosthetic_list_bloc_test.dart"
  "test/bloc/prosthetic_case_detail_bloc_test.dart"
  "test/bloc/prosthetic_status_bloc_test.dart"
  "test/bloc/prosthetic_payment_bloc_test.dart"
  "test/bloc/waiting_placement_bloc_test.dart"
  "test/bloc/alert_list_bloc_test.dart"
  "test/bloc/sync_status_bloc_test.dart"

  # ----- test/widget -----
  "test/widget/login_screen_test.dart"
  "test/widget/dashboard_screen_test.dart"
  "test/widget/label_detail_screen_test.dart"
  "test/widget/label_blocked_screen_test.dart"
  "test/widget/cycle_detail_screen_test.dart"
  "test/widget/prosthetic_case_detail_test.dart"
  "test/widget/prosthetic_form_test.dart"
  "test/widget/waiting_placement_screen_test.dart"
  "test/widget/sync_status_banner_test.dart"

  # ----- test/golden -----
  "test/golden/login_screen_golden_test.dart"
  "test/golden/dashboard_screen_golden_test.dart"
  "test/golden/label_detail_golden_test.dart"
  "test/golden/prosthetic_case_detail_golden_test.dart"

  # ----- test/fixtures -----
  "test/fixtures/user_fixture.dart"
  "test/fixtures/tenant_fixture.dart"
  "test/fixtures/label_fixture.dart"
  "test/fixtures/cycle_fixture.dart"
  "test/fixtures/prosthetic_case_fixture.dart"
  "test/fixtures/payment_fixture.dart"
  "test/fixtures/laboratory_fixture.dart"
  "test/fixtures/waiting_placement_fixture.dart"

  # ----- test/mocks -----
  "test/mocks/mock_dio.dart"
  "test/mocks/mock_outbox_store.dart"
  "test/mocks/mock_connectivity.dart"
  "test/mocks/mock_repositories.dart"

  # ----- test/helpers -----
  "test/helpers/pump_app.dart"
  "test/helpers/test_di.dart"
  "test/helpers/golden_config.dart"

  # ----- integration_test -----
  "integration_test/app_test.dart"
  "integration_test/journeys/auth_journey_test.dart"
  "integration_test/journeys/scanner_usage_journey_test.dart"
  "integration_test/journeys/cycle_lifecycle_journey_test.dart"
  "integration_test/journeys/prosthetic_case_journey_test.dart"
  "integration_test/journeys/waiting_placement_journey_test.dart"
  "integration_test/journeys/stock_issue_journey_test.dart"
  "integration_test/journeys/goods_receipt_journey_test.dart"
  "integration_test/journeys/alert_resolve_journey_test.dart"
  "integration_test/journeys/offline_sync_journey_test.dart"
  "integration_test/journeys/conflict_409_journey_test.dart"
  "integration_test/support/backend_seed.dart"
  "integration_test/support/backend_reset.dart"
  "integration_test/support/test_user.dart"
  "integration_test/support/test_data.dart"
  "integration_test/drivers/integration_test_driver.dart"

  # ----- scripts -----
  "scripts/bootstrap.sh"
  "scripts/dev.sh"
  "scripts/run_staging.sh"
  "scripts/run_production.sh"
  "scripts/build_android_debug.sh"
  "scripts/build_android_release.sh"
  "scripts/build_android_aab.sh"
  "scripts/build_ios_debug.sh"
  "scripts/build_ios_release.sh"
  "scripts/build_ios_ipa.sh"
  "scripts/test_unit.sh"
  "scripts/test_bloc.sh"
  "scripts/test_widget.sh"
  "scripts/test_golden.sh"
  "scripts/test_integration.sh"
  "scripts/test_all.sh"
  "scripts/analyze.sh"
  "scripts/format.sh"
  "scripts/gen_l10n.sh"
  "scripts/gen_icons.sh"
  "scripts/gen_splash.sh"
  "scripts/clean.sh"
  "scripts/bump_version.sh"
  "scripts/release.sh"

  # ----- fastlane -----
  "fastlane/Fastfile"
  "fastlane/Appfile"
  "fastlane/Matchfile"
  "fastlane/Pluginfile"
  "fastlane/metadata/android/fr-FR/title.txt"
  "fastlane/metadata/android/fr-FR/short_description.txt"
  "fastlane/metadata/android/fr-FR/full_description.txt"
  "fastlane/metadata/android/fr-FR/changelogs/default.txt"
  "fastlane/metadata/ios/fr-FR/name.txt"
  "fastlane/metadata/ios/fr-FR/subtitle.txt"
  "fastlane/metadata/ios/fr-FR/description.txt"
  "fastlane/metadata/ios/fr-FR/keywords.txt"
  "fastlane/metadata/ios/fr-FR/release_notes.txt"
  "fastlane/metadata/ios/fr-FR/support_url.txt"
  "fastlane/certs/README.md"

  # ----- .github -----
  ".github/workflows/mobile-analyze.yml"
  ".github/workflows/mobile-test.yml"
  ".github/workflows/mobile-build-android.yml"
  ".github/workflows/mobile-build-ios.yml"
  ".github/workflows/mobile-release-android.yml"
  ".github/workflows/mobile-release-ios.yml"
  ".github/workflows/secrets-scan.yml"

  # ----- docs -----
  "docs/README.md"
  "docs/ARCHITECTURE.md"
  "docs/API_CONTRACT.md"
  "docs/UI_MAPPING.md"
  "docs/OFFLINE_MATRIX.md"
  "docs/ERROR_MATRIX.md"
  "docs/ROLE_MATRIX.md"
  "docs/SECURITY.md"
  "docs/PRIVACY.md"
  "docs/PERFORMANCE.md"
  "docs/TESTING.md"
  "docs/CICD.md"
  "docs/RELEASE.md"
  "docs/RUNBOOK.md"
  "docs/BACKUP_RESTORE.md"
  "docs/SUPPORT.md"
  "docs/MIGRATION.md"
  "docs/LOCALIZATION.md"
  "docs/PROSTHETIC_MODULE.md"
  "docs/DEVICE_TEST_LOG.md"
  "docs/DAILY_LOG.md"
  "docs/DEMO_SCRIPT.md"
  "docs/USER_GUIDE.md"

  # ----- root files -----
  "CHANGELOG.md"
  "LICENSE"
  "Makefile"
  "l10n.yaml"
  "dart_test.yaml"
)

for f in "${files[@]}"; do
  mkdir -p "$(dirname "$f")"
  [ -f "$f" ] || touch "$f"
done
echo "   ✓ ${#files[@]} files"

# ===================================================================
# Restore main.dart if it was backed up
# ===================================================================
if [ -f "$HOME/main.dart.bak" ] && [ ! -s "lib/main.dart" ]; then
  cp "$HOME/main.dart.bak" lib/main.dart
  echo "   ✓ lib/main.dart restored"
fi

echo ""
echo "🎉 Global Ultimate tree scaffolded."
echo "   Next: flutter pub get"