import 'package:steriymed_mobile/core/config/env.dart';

/// Generated by the isolated clinic fixture kit. No demo-account fallback.
abstract final class TestUser {
  static const config = FixtureTestConfig(
    apiBaseUrl: Env.apiBaseUrl,
    environment: Env.environment,
    fixtureId: String.fromEnvironment('TEST_FIXTURE_ID'),
    tenantSlug: String.fromEnvironment('TEST_TENANT_SLUG'),
    tenantId: String.fromEnvironment('TEST_TENANT_ID'),
    adminEmail: String.fromEnvironment('TEST_ADMIN_EMAIL'),
    adminPassword: String.fromEnvironment('TEST_ADMIN_PASSWORD'),
    deviceName: String.fromEnvironment('TEST_DEVICE_NAME'),
    deviceId: String.fromEnvironment('TEST_DEVICE_ID'),
    programId: String.fromEnvironment('TEST_PROGRAM_ID'),
  );

  static String get tenantSlug => config.tenantSlug;
  static String get adminEmail => config.adminEmail;
  static String get adminPassword => config.adminPassword;
  static String get deviceName => config.deviceName;
}

class FixtureTestConfig {
  static const expectedFixtureId = 'sterymed-clinic-fixture-v1';
  static const expectedDatabase = 'steriqore_mobile_fixture';

  final String apiBaseUrl;
  final String environment;
  final String fixtureId;
  final String tenantSlug;
  final String tenantId;
  final String adminEmail;
  final String adminPassword;
  final String deviceName;
  final String deviceId;
  final String programId;

  const FixtureTestConfig({
    required this.apiBaseUrl,
    required this.environment,
    required this.fixtureId,
    required this.tenantSlug,
    required this.tenantId,
    required this.adminEmail,
    required this.adminPassword,
    required this.deviceName,
    required this.deviceId,
    required this.programId,
  });

  Uri get markerUri {
    validate();
    return Uri.parse(apiBaseUrl).replace(path: '/__clinic_fixture');
  }

  void validate() {
    final uri = Uri.tryParse(apiBaseUrl);
    if (environment != 'dev' ||
        uri == null ||
        !{'http', 'https'}.contains(uri.scheme) ||
        !{'localhost', '127.0.0.1', '10.0.2.2', '::1'}.contains(uri.host) ||
        uri.port != 18010 ||
        !{'/api', '/api/'}.contains(uri.path) ||
        uri.userInfo.isNotEmpty ||
        uri.hasQuery ||
        uri.hasFragment) {
      throw StateError(
        'Live journeys require the isolated fixture API on local port 18010 '
        'with ENV=dev. Use the generated flutter_defines.json.',
      );
    }
    if (fixtureId != expectedFixtureId ||
        tenantSlug.isEmpty ||
        tenantId.isEmpty ||
        !adminEmail.endsWith('.example.invalid') ||
        adminPassword.isEmpty ||
        deviceName.isEmpty ||
        deviceId.isEmpty ||
        programId.isEmpty) {
      throw StateError(
        'Missing or invalid synthetic fixture identities. Seed the fixture '
        'and pass --dart-define-from-file=build/clinic-fixture/flutter_defines.json.',
      );
    }
  }
}
